apiVersion: v1
kind: Service
metadata:
  name: {{ include "skillsd.fullname" . }}
  labels:
    {{- include "skillsd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "skillsd.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      name: grpc
